version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8008:8000
    env_file:
      - ./.env
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
