version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8008:8000
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password123
      - DATABASE_PORT=5432

  postgres:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
