"""add phone_number column in posts table

Revision ID: 682c49381583
Revises: b9359a9b492f
Create Date: 2021-11-20 19:25:38.877682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682c49381583'
down_revision = 'b9359a9b492f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'phone_number')
    # ### end Alembic commands ###
